
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>4. Exceptions &#8212; Object Oriented Programmming with Python  documentation</title>
    <link rel="stylesheet" href="_static/alabaster.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="5. Classes and Instances" href="exercise-5.html" />
    <link rel="prev" title="3. Functions" href="exercise-3.html" />
   
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
  
  
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head><body>
  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          

          <div class="body" role="main">
            
  <div class="section" id="exceptions">
<h1>4. Exceptions<a class="headerlink" href="#exceptions" title="Permalink to this headline">¶</a></h1>
<p>We’ve already seen a bunch of times what happens in Python when things go wrong:</p>
<div class="highlight-pycon notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="mi">3</span> <span class="o">+</span> <span class="s2">&quot;not a number&quot;</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for +: &#39;int&#39; and &#39;str&#39;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="s1">&#39;foo&#39;</span><span class="p">:</span> <span class="s1">&#39;bar&#39;</span><span class="p">}</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">a</span><span class="p">[</span><span class="s1">&#39;bam&#39;</span><span class="p">]</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">KeyError</span>: <span class="n">&#39;bam&#39;</span>
</pre></div>
</div>
<p>These are called “exceptions” and they’re the way that Python signals to you that something went wrong. Different types of errors have different types of exceptions. In the first example above we get a <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> because you can’t add strings to numbers (they’re the wrong type) and in the second we get a <code class="docutils literal notranslate"><span class="pre">KeyError</span></code> because the key we looked up in the dictionary didn’t exist. Normally an unhandled exception will end your program, literally bringing it to a halt with a crash. Some kinds of error we expect though and can even do something about. Python provides a way of catching exceptions, and if we need to even raising new exceptions ourselves.</p>
<p>Exceptions are important in programming because things are <em>always</em> going wrong. Sometimes there’s even something you can do about it.</p>
<p>The basic syntax for catching an exception is called <code class="docutils literal notranslate"><span class="pre">try..</span> <span class="pre">except</span></code>. It gives us two blocks of code. Everything inside  the try block is protected by the except and if the right kind of exception is raised then the code inside the except block is executed. Here’s a very simple example.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">foo</span> <span class="c1"># this name doesn&#39;t exist</span>
<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&quot;We got a NameError because foo doesn&#39;t exist&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p>The trouble with this kind of exception handling is that it catches every error and it doesn’t even tell us what went wrong. We can do better than that, we can catch only specific exceptions and we can get hold of the exception object itself (yes, even exceptions are objects in Python) and have a look at it.</p>
<div class="highlight-pycon notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>   <span class="n">foo</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>   <span class="k">print</span><span class="p">(</span><span class="nb">type</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
<span class="gp">... </span>   <span class="k">print</span><span class="p">(</span><span class="nb">str</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
<span class="gp">...</span>
<span class="go">&lt;class &#39;NameError&#39;&gt;</span>
<span class="go">name &#39;foo&#39; is not defined</span>
</pre></div>
</div>
<p>Here <code class="docutils literal notranslate"><span class="pre">e</span></code> is the <em>specific</em> exception being raised (the exception instance - the error represented as an object). We can examine <code class="docutils literal notranslate"><span class="pre">e</span></code> inside the except block to find more information about it.</p>
<p>If we’re sure we can’t actually handle it we can even re-raise it again:</p>
<div class="highlight-pycon notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>   <span class="n">foo</span>
<span class="gp">... </span><span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>   <span class="k">print</span><span class="p">(</span><span class="nb">type</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
<span class="gp">... </span>   <span class="k">print</span><span class="p">(</span><span class="nb">str</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>
<span class="gp">... </span>   <span class="k">raise</span>
<span class="gp">...</span>
<span class="go">&lt;class &#39;NameError&#39;&gt;</span>
<span class="go">name &#39;foo&#39; is not defined</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">NameError</span>: <span class="n">name &#39;foo&#39; is not defined</span>
</pre></div>
</div>
<p>Usually turning the exception into a string gives you a good idea of what went wrong. <code class="docutils literal notranslate"><span class="pre">Exception</span></code> is the most basic type of error there is, it will catch pretty much any kind of error that can happen. Usually there’s only one or two specific errors we’re interested in and can recover from. For example suppose we want to read data from a file, but if the file doesn’t exist we can just use some default data instead. In this example we’ll try and read some data and substitute our own if the file doesn’t exist.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;foo.txt&quot;</span><span class="p">)</span> <span class="k">as</span> <span class="n">handle</span><span class="p">:</span>
        <span class="n">data</span> <span class="o">=</span> <span class="n">handle</span><span class="o">.</span><span class="n">read</span><span class="p">()</span>
<span class="k">except</span> <span class="n">FileNotFoundError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&quot;Missing foo.txt&quot;</span><span class="p">)</span>
    <span class="n">data</span> <span class="o">=</span> <span class="s2">&quot;&quot;</span>
</pre></div>
</div>
<p>Here’s we’re <em>only</em> catching the <code class="docutils literal notranslate"><span class="pre">FileNotFoundError</span></code>. Any other error will still cause the program to crash. Usually this is what you want. You don’t want unexpected errors to be ignored and the program to carry on running as if nothing went wrong. In Python we call this principle “errors should never pass silently unless expicitly silenced”. For more wonderful and pithy comments on Python programming try this at the interactive interpreter:</p>
<div class="highlight-pycon notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span> <span class="nn">this</span>
</pre></div>
</div>
<p>There’s a huge number of built-in exceptions and many modules and libraries define their own as well.</p>
<p>Here’s a list of some of them:</p>
<ul class="simple">
<li><a class="reference external" href="https://docs.python.org/3/library/exceptions.html">https://docs.python.org/3/library/exceptions.html</a></li>
</ul>
<p>Using sub-classing (a feature of object orientation called “inheritance”) we can even create our own exceptions. More on that later hopefully.</p>
<p>There’s a lot more to exceptions, we can have multiple <code class="docutils literal notranslate"><span class="pre">except</span></code> blocks for handling different exceptions differently in the same block of code, we can catch several different types of exceptions in the same except block and we can even have code that runs whether or not an exception occurred (the <code class="docutils literal notranslate"><span class="pre">finally</span></code> block).</p>
</div>


          </div>
          
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
<h1 class="logo"><a href="index.html">Object Oriented Programmming with Python</a></h1>








<h3>Navigation</h3>
<ul class="current">
<li class="toctree-l1"><a class="reference internal" href="exercise-0.html">0. IDLE &amp; the Interactive Interpreter</a></li>
<li class="toctree-l1"><a class="reference internal" href="exercise-1.html">1. Numbers and Strings</a></li>
<li class="toctree-l1"><a class="reference internal" href="exercise-2.html">2. Collections and Containers</a></li>
<li class="toctree-l1"><a class="reference internal" href="exercise-3.html">3. Functions</a></li>
<li class="toctree-l1 current"><a class="current reference internal" href="#">4. Exceptions</a></li>
<li class="toctree-l1"><a class="reference internal" href="exercise-5.html">5. Classes and Instances</a></li>
<li class="toctree-l1"><a class="reference internal" href="exercise-6.html">6. Types, Properties and Private Members</a></li>
<li class="toctree-l1"><a class="reference internal" href="exercise-7.html">7. Interfaces and APIs</a></li>
<li class="toctree-l1"><a class="reference internal" href="exercise-8.html">8. Operator Overloading and the Python Protocols</a></li>
</ul>

<div class="relations">
<h3>Related Topics</h3>
<ul>
  <li><a href="index.html">Documentation overview</a><ul>
      <li>Previous: <a href="exercise-3.html" title="previous chapter">3. Functions</a></li>
      <li>Next: <a href="exercise-5.html" title="next chapter">5. Classes and Instances</a></li>
  </ul></li>
</ul>
</div>
<div id="searchbox" style="display: none" role="search">
  <h3>Quick search</h3>
    <div class="searchformwrapper">
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>








        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="footer">
      &copy;2018, Michael Foord.
      
      |
      Powered by <a href="http://sphinx-doc.org/">Sphinx 1.8.2</a>
      &amp; <a href="https://github.com/bitprophet/alabaster">Alabaster 0.7.12</a>
      
      |
      <a href="_sources/exercise-4.txt"
          rel="nofollow">Page source</a>
    </div>

    

    
  </body>
</html>